# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1aaad83
_src_path: git@github.com:invofox/value-proposition-template.git
default_implementation: Delete
git_branch: FIFA-946_Invofox-region-benchmark-scripts
git_repo: git@github.com:invofox/OmniDocBench.git
python_version: '3.10'
repo_name: OmniDocBench
submodule_name: delete
vp_description: Public Invoice Region Benchmark
vp_name: OmniDocBench
